# See doc/docker/README.md or https://github.com/instructure/canvas-lms/tree/master/doc/docker
version: '2.3'
services:
  jobs: &BASE
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - api_docs:/usr/src/app/public/doc/api
      - brandable_css_brands:/usr/src/app/app/stylesheets/brandable_css_brands
      - bundler:/home/docker/.bundle/
      - canvas-docker-gems:/home/docker/.gem/
      - canvas-media_es:/usr/src/app/packages/canvas-media/es
      - canvas-media_lib:/usr/src/app/packages/canvas-media/lib
      - canvas-media_node_modules:/usr/src/app/packages/canvas-media/node_modules
      - canvas-planner_node_modules:/usr/src/app/packages/canvas-planner/node_modules
      - canvas-planner_lib:/usr/src/app/packages/canvas-planner/lib
      - canvas-rce_canvas:/usr/src/app/packages/canvas-rce/canvas
      - canvas-rce_lib:/usr/src/app/packages/canvas-rce/lib
      - canvas-rce_node_modules:/usr/src/app/packages/canvas-rce/node_modules
      - jest-moxios-utils_node_modules:/usr/src/app/packages/jest-moxios-utils/node_modules
      - js-utils_es:/usr/src/app/packages/js-utils/es
      - js-utils_lib:/usr/src/app/packages/js-utils/lib
      - js-utils_node_modules:/usr/src/app/packages/js-utils/node_modules
      - k5uploader_es:/usr/src/app/packages/k5uploader/es
      - k5uploader_lib:/usr/src/app/packages/k5uploader/lib
      - k5uploader_node_modules:/usr/src/app/packages/k5uploader/node_modules
      - locales:/usr/src/app/config/locales/generated
      - log:/usr/src/app/log
      - node_modules:/usr/src/app/node_modules
      - old-copy-of-react-14-that-is-just-here-so-if-analytics-is-checked-out-it-doesnt-change-yarn.lock_node_modules:/usr/src/app/packages/old-copy-of-react-14-that-is-just-here-so-if-analytics-is-checked-out-it-doesnt-change-yarn.lock/node_modules
      - pacts:/usr/src/app/pacts
      - public_dist:/usr/src/app/public/dist
      - reports:/usr/src/app/reports
      - styleguide:/usr/src/app/app/views/info
      - tmp:/usr/src/app/tmp
      - translations:/usr/src/app/public/javascripts/translations
      - yardoc:/usr/src/app/.yardoc
      - yarn-cache:/home/docker/.cache/yarn
    environment: &BASE-ENV
      ENCRYPTION_KEY: facdd3a131ddd8988b14f6e4e01039c93cfa0160
      RAILS_ENV: development

  webpack:
    <<: *BASE
    command: yarn run webpack
    env_file:
      - ./.env

  web:
    <<: *BASE
    environment:
      <<: *BASE-ENV
      VIRTUAL_HOST: .canvas.docker
      HTTPS_METHOD: noredirect
      # AR_QUERY_TRACE: 'true'
      # AR_QUERY_TRACE_TYPE: 'all' # 'all', 'write', or 'read'
      # AR_QUERY_TRACE_LINES: 10
    ports:
      - "9100:80"

  postgres:
    volumes:
      - pg_data:/var/lib/postgresql/data

  githook_installer:
    build:
      context: .
      dockerfile: 'Dockerfile.githook'
    volumes:
      - ./.git:/tmp/.git
      - ./hooks:/tmp/hooks
      - ./script:/tmp/script

  socat:
    image: alpine/socat:1.7.4.3-r1
    depends_on:
      - web
    command: "TCP-LISTEN:9100,fork,reuseaddr TCP:web:80"
    networks:
      default:
        aliases:
          - socat
      docker_canvas_bridge:
        aliases:
          - canvas.docker

networks:
  docker_canvas_bridge:
    name: docker_canvas_bridge

volumes:
  api_docs: {}
  brandable_css_brands: {}
  bundler: {}
  canvas-docker-gems: {}
  canvas-media_es: {}
  canvas-media_lib: {}
  canvas-media_node_modules: {}
  canvas-planner_node_modules: {}
  canvas-planner_lib: {}
  canvas-rce_canvas: {}
  canvas-rce_lib: {}
  canvas-rce_node_modules: {}
  i18nliner_node_modules: {}
  jest-moxios-utils_node_modules: {}
  js-utils_es: {}
  js-utils_lib: {}
  js-utils_node_modules: {}
  k5uploader_es: {}
  k5uploader_lib: {}
  k5uploader_node_modules: {}
  locales: {}
  log: {}
  node_modules: {}
  old-copy-of-react-14-that-is-just-here-so-if-analytics-is-checked-out-it-doesnt-change-yarn.lock_node_modules: {}
  pg_data: {}
  pacts: {}
  public_dist: {}
  reports: {}
  styleguide: {}
  tmp: {}
  translations: {}
  yardoc: {}
  yarn-cache: {}
